import type { MerchItem } from "./merch";

export const merchHero = {
  eyebrow: "De Kam Sun",
  title: "Foundry Gudz.",
  body:
    "Wɛarabul ɛn ɛvride tin dɛn we kyas frɔm di sem studio we mek di wok — wan fizikal ɛkstɛnshɔn fɔ di brand, nɔ wan webstɔ afta-tot.",
};

export const merchCopy = {
  all: "Ɔl",
  addToCart: "Ad to kat",
  addedToCart: "Ad ✓",
  outOfStock: "I dɔn dɔn",
  selectSize: "Pik sayz",
  selectSizePrompt: "Pik wan sayz fɔ ad dis to yu kat.",
  size: "Sayz",
  quantity: "Kwantiti",
  careInstructions: "Kea Instrɔkshɔn",
  moreDetails: "Mɔ Ditel",
  returnsGuarantee: "Ritɔn Ɛn Gyarantii",
  returnsDefault:
    "Di stɔ nɔ dɔn opin fɔ ɔda yet — wan rial ritɔn polisi go pɔblish wɛn i opin.",
  breadcrumbHome: "Om",
  breadcrumbMerch: "Merch",
  yourCart: "Yu Kat",
  emptyCart: "Yu kat nɔ gɛt natin.",
  remove: "Rimuv",
  subtotal: "Sɔbtotal",
  checkout: "Chɛkaut",
  checkoutComingSoon: "Chɛkaut nɔ dɔn opin yet — dis kat na jɔs privyu.",
  continueShopping: "Kɔntinyu brawz",
};

// Product names, care/details copy stay descriptive; names are proper
// nouns and stay in English, matching the work/journal convention.
export const merchItems: MerchItem[] = [
  {
    slug: "foundry-tee",
    name: "The Foundry Tee",
    category: "Apparel",
    description:
      "Ɛvi kɔtɔn, skrin-prin insay studio. Di mak, nɔ di noyz — kɔt fɔ ɛvride wea, bil fɔ las pas di sizin we i lɔnch.",
    price: 450,
    stockQuantity: 40,
    images: ["Front", "Back", "Detail", "Lifestyle", "Flat Lay"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    careInstructions: "Mashin wash kol, insay-aut. Tɔmbul dray lo. Nɔ ayɔn di prin.",
    details: "100% kɔmb kɔtɔn, 180gsm. Skrin-prin na Fritɔn.",
  },
  {
    slug: "heavyweight-hoodie",
    name: "Heavyweight Hoodie",
    category: "Apparel",
    description:
      "Garmɛnt-day flis wit brɔsh insay, bil fɔ lɔng edit-be nyt dɛn ɛn di wɔk go os afta. Kɔt rileks, nɔ bɔksi.",
    price: 950,
    stockQuantity: 25,
    images: ["Front", "Back", "Detail", "Lifestyle", "Flat Lay"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    careInstructions: "Mashin wash kol wit sem kɔlɔ dɛn. Tɔmbul dray lo. Nɔ ayɔn di prin.",
    details: "80/20 kɔtɔn-poli flis, 320gsm. Brɔsh insay, kanguru pɔket.",
  },
  {
    slug: "foundry-cap",
    name: "Foundry Cap",
    category: "Apparel",
    description:
      "Wan lo-profayl, strɔktɔ siks-panɛl kap. Ɛmbrɔyda — nɔ prin — fɔ wan mak we ol ɔp to wɛda ɛn wash.",
    price: 350,
    stockQuantity: 30,
    images: ["Front", "Side", "Back", "Detail", "Lifestyle"],
    careInstructions: "Spɔt klin ɔnli. Nɔ mashin wash ɔ tɔmbul dray — strɔkchɔ nɔ go ol.",
    details: "Kɔtɔn twil, adjɔstabul strap, wan sayz fit ɔlmost ɛvribɔdi.",
  },
  {
    slug: "studio-tote",
    name: "Studio Tote",
    category: "Accessories",
    description:
      "Ɛvi kanvas bil fɔ kyari di sem lod lɛk kamra gia. Rinfɔs andul dɛn, wan flat bes, rum fɔ laptɔp ɛn di rɛst ɔf di kit.",
    price: 300,
    stockQuantity: 35,
    images: ["Front", "Interior", "Detail", "Lifestyle", "Flat Lay"],
    careInstructions: "Spɔt klin ɔ an wash kol. Ea dray.",
    details: "12oz kɔtɔn kanvas, rinfɔs stich, 40cm x 38cm.",
  },
  {
    slug: "cast-mark-stickers",
    name: "Cast Mark Sticker Sheet",
    category: "Accessories",
    description: "Wan shit ɔf studio mak dɛn fɔ laptɔp, kes, ɛn gia. Mat vinil, wɛda-pruf, kɔt klin.",
    price: 90,
    stockQuantity: 60,
    images: ["Full Sheet", "Detail", "Applied — Laptop", "Applied — Case"],
    details: "Wɔtapruf mat vinil, UV-rizistant. Wan-wan day-kɔt, pil ɛn put.",
  },
  {
    slug: "enamel-pin-set",
    name: "Enamel Pin Set",
    category: "Accessories",
    description: "Tri smɔl mak dɛn na ad enamel, fɔ jaket, strap, ɛn lanyad. Dɛn sɛl am as wan sɛt.",
    price: 150,
    stockQuantity: 45,
    images: ["Full Set", "Detail", "Applied — Jacket", "Applied — Strap"],
    details: "Ad enamel wit bataflay klɔch bakin. Sɛt ɔf tri pin.",
  },
  {
    slug: "studio-mug",
    name: "Studio Mug",
    category: "Drinkware",
    description:
      "Stonwea, glez na studio kɔlɔ dɛn, i ol di kɔfi we ol di dedlayn. Dishwasha ɛn maykrowev sef.",
    price: 250,
    stockQuantity: 30,
    images: ["Front", "Side", "Detail", "Lifestyle"],
    careInstructions: "Dishwasha ɛn maykrowev sef. Di glez fɔ dal small small pas plɛnti ia we yu de yus am.",
    details: "350ml stonwea, glez awtsayd ɛn insay.",
  },
  {
    slug: "field-notebook",
    name: "Field Notebook",
    category: "Stationery",
    description:
      "Dɔt-grid pej dɛn we bayn insay wan strɔng kɔva, sayz fɔ skrip, shɔt lis, ɛn af-fɔm aydiya dɛn. I de lay flat wɛn opin.",
    price: 200,
    stockQuantity: 50,
    images: ["Cover", "Open — Pages", "Detail", "Lifestyle"],
    details: "80 dɔt-grid pej, 100gsm pepa. Ilastik klozha, ribin bukmak.",
  },
  {
    slug: "foundry-crewneck",
    name: "Foundry Crewneck",
    category: "Apparel",
    description:
      "Mid-wet flis kruneck, brɔsh insay. I sidɔm bitwin di ti-shɔt ɛn di hudi — fɔ di de dɛn we nid wan lili mɔ.",
    price: 700,
    stockQuantity: 28,
    images: ["Front", "Back", "Detail", "Lifestyle", "Flat Lay"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    careInstructions: "Mashin wash kol wit sem kɔlɔ dɛn. Tɔmbul dray lo.",
    details: "80/20 kɔtɔn-poli flis, 280gsm. Rib kɔf ɛn ɛm.",
  },
  {
    slug: "foundry-long-sleeve-tee",
    name: "Foundry Long Sleeve",
    category: "Apparel",
    description:
      "Di sem ɛvi kɔtɔn lɛk di ti-shɔt, kɔt lɔng fɔ di sizin we di studio actually shɔt.",
    price: 500,
    stockQuantity: 35,
    images: ["Front", "Back", "Detail", "Lifestyle", "Flat Lay"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    careInstructions: "Mashin wash kol, insay-aut. Tɔmbul dray lo. Nɔ ayɔn di prin.",
    details: "100% kɔmb kɔtɔn, 180gsm. Skrin-prin na Fritɔn.",
  },
  {
    slug: "foundry-track-jacket",
    name: "Foundry Track Jacket",
    category: "Apparel",
    description: "Wan lay jaket we bil fɔ sɛt — i kɔva ɔva ɛnitin, i pak sɔ smɔl.",
    price: 850,
    stockQuantity: 20,
    images: ["Front", "Back", "Detail", "Lifestyle", "Flat Lay"],
    sizes: ["S", "M", "L", "XL", "2XL"],
    careInstructions: "Mashin wash kol. Ang dray — nɔ tɔmbul dray.",
    details: "Ripstɔp shɛl, mesh laynin, ful zip. Wɔta-rizistant finish.",
  },
  {
    slug: "foundry-beanie",
    name: "Foundry Beanie",
    category: "Apparel",
    description: "Rib nit, ɛmbrɔyda mak. Wan sayz, bil fɔ Fritɔn in tu rial sizin dɛn.",
    price: 250,
    stockQuantity: 40,
    images: ["Front", "Side", "Detail", "Lifestyle"],
    careInstructions: "An wash kol. Le am flat fɔ dray.",
    details: "Akrilik-wul miks, rib nit, ɛmbrɔyda mak.",
  },
  {
    slug: "studio-laptop-sleeve",
    name: "Studio Laptop Sleeve",
    category: "Accessories",
    description: "Pad niopren sayz fɔ 14-in machin, wit rum fɔ wan ɔ tu keb.",
    price: 320,
    stockQuantity: 30,
    images: ["Front", "Interior", "Detail", "Lifestyle"],
    details: "Pad niopren, fit ɔp to 14-in laptɔp dɛn. Zip klozha.",
  },
  {
    slug: "cast-mark-keychain",
    name: "Cast Mark Keychain",
    category: "Accessories",
    description: "Wan smɔl kyas-mɛtal vɛshɔn ɔf di studio mak, fɔ ki, bag, ɔ kamra strap.",
    price: 120,
    stockQuantity: 55,
    images: ["Detail", "Applied — Bag", "Applied — Keys"],
    details: "Kyas zink aloy, antik finish, split rin.",
  },
  {
    slug: "foundry-camera-strap",
    name: "Foundry Camera Strap",
    category: "Accessories",
    description: "Webin strap we bil to di sem spɛk di kru actually de yus, nɔ jɔs wan displey pis.",
    price: 280,
    stockQuantity: 25,
    images: ["Full", "Detail", "Applied — Camera"],
    details: "Naylɔn webin, lɛda ɛn, kwik-rilis bɔkul.",
  },
  {
    slug: "studio-pouch",
    name: "Studio Pouch",
    category: "Accessories",
    description: "Kanvas zip paus fɔ keb, kad, ɛn di smɔl tin dɛn we go mis fɔs.",
    price: 180,
    stockQuantity: 35,
    images: ["Front", "Interior", "Detail", "Lifestyle"],
    details: "12oz kɔtɔn kanvas, wɔta-rizistant zip, 18cm x 12cm.",
  },
  {
    slug: "studio-travel-tumbler",
    name: "Studio Travel Tumbler",
    category: "Drinkware",
    description: "Insyuletid stenlɛs stil, i kip kɔfi at pas wan ful mɔnin shut.",
    price: 320,
    stockQuantity: 25,
    images: ["Front", "Detail", "Lifestyle"],
    careInstructions: "An wash ɔnli. Nɔ maykrowev am.",
    details: "473ml dɔbul-wɔl stenlɛs stil, lik-pruf lid.",
  },
  {
    slug: "foundry-water-bottle",
    name: "Foundry Water Bottle",
    category: "Drinkware",
    description: "Dɔbul-wɔl stenlɛs stil, 750ml, sayz fɔ wan ful de aut ɔf di studio.",
    price: 280,
    stockQuantity: 30,
    images: ["Front", "Detail", "Lifestyle"],
    careInstructions: "An wash ɔnli. Nɔ maykrowev am.",
    details: "750ml dɔbul-wɔl stenlɛs stil, paudakot finish.",
  },
  {
    slug: "foundry-desk-pad",
    name: "Foundry Desk Pad",
    category: "Stationery",
    description: "Wan big-fɔmat dɛsk pad fɔ not, sketch, ɛn aydiya dɛn we nɔ fit insay wan notbuk pej.",
    price: 220,
    stockQuantity: 30,
    images: ["Full", "Detail", "Lifestyle"],
    details: "50 tia-awe shit, 40cm x 30cm, kraft bakin.",
  },
  {
    slug: "foundry-postcard-set",
    name: "Foundry Postcard Set",
    category: "Stationery",
    description: "Wan sɛt ɔf tɛn poskad we kɔmɔt frɔm di studio in on frem-grab dɛn.",
    price: 80,
    stockQuantity: 45,
    images: ["Full Set", "Detail", "Lifestyle"],
    details: "Sɛt ɔf 10, 300gsm mat kad stɔk, 10cm x 15cm.",
  },
];
