import { defineType, defineField } from "sanity";

// Mirrors WorkCategory in lib/content/work.ts — keep both lists in sync.
const WORK_CATEGORIES = [
  "Brand Identity",
  "Campaigns",
  "Film & Production",
  "Digital",
  "Photography",
  "Social & Content",
  "Music Video",
  "Video Podcast",
  "Activation",
  "Cinematography & Photography",
];

export const workItem = defineType({
  name: "workItem",
  title: "Work item",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "layout", title: "Advanced / layout" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      description: "Client/project name — shown the same in both languages.",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "hoverTitle",
      title: "Short title (for the hover card)",
      type: "string",
      description: "Only needed when the full title is too long for the hover overlay, e.g. \"FemCo\".",
      group: "content",
    }),
    defineField({
      name: "category",
      title: "Category",
      type: "string",
      options: { list: WORK_CATEGORIES },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "localeText",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "client", title: "Client (if different from the title)", type: "string", group: "content" }),
    defineField({
      name: "variant",
      title: "Variant",
      type: "string",
      options: { list: ["video", "photo"] },
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "size",
      title: "Grid size",
      type: "string",
      options: { list: ["md", "lg"] },
      description: "\"lg\" reads as a hero cell in the contact-sheet grid.",
      group: "content",
      initialValue: "md",
    }),
    defineField({
      name: "hasCaseStudy",
      title: "Has a case-study page",
      type: "boolean",
      initialValue: false,
      group: "content",
    }),
    defineField({
      name: "restingImage",
      title: "Image",
      type: "image",
      options: { hotspot: true },
      group: "content",
      description: "The client's real logo or artwork. Without one, the site shows a placeholder frame.",
    }),
    defineField({
      name: "hoverImage",
      title: "Hover-reveal logo",
      type: "image",
      group: "content",
      description: "Small logo shown inside the coloured hover overlay.",
    }),
    defineField({
      name: "imageFit",
      title: "Image fit",
      type: "string",
      options: { list: ["cover", "contain"] },
      description: "\"contain\" for a logo that needs breathing room on a white field; \"cover\" for a full-bleed photo.",
      group: "layout",
      initialValue: "cover",
    }),
    defineField({
      name: "imagePadding",
      title: "Image padding (advanced)",
      type: "string",
      description: "Raw Tailwind classes, e.g. \"p-10\". Developer-authored — leave alone unless you know what this does.",
      group: "layout",
    }),
    defineField({
      name: "hoverImageSize",
      title: "Hover logo size (advanced)",
      type: "string",
      description: "Raw Tailwind classes for the hover-reveal logo. Developer-authored.",
      group: "layout",
    }),
    defineField({ name: "order", title: "Order", type: "number", group: "content" }),
  ],
  orderings: [{ title: "Order", name: "orderAsc", by: [{ field: "order", direction: "asc" }] }],
  preview: {
    select: { title: "title", subtitle: "category", media: "restingImage" },
  },
});
